version: '3.7'

services:

  front:
    image: react
    container_name: react
    build:
      context: ../front
    volumes:
      - ../front:/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      - my-network
  php-fpm:
    image: symfony
    container_name: symfony
    build:
      context: php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - TEST_NAME=${TEST_NAME}
    volumes:
      - ../back:/var/www
    networks:
      - my-network
  nginx:
    image: nginx-server
    container_name: server
    build:
      context: nginx
    volumes:
      - ../back:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network: